// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma contract emit'.
// To regenerate, run: prisma contract emit
import type { QueryOperationTypes as PgAdapterQueryOps } from '@prisma/orm-postgres/adapter/operation-types';
import type {
  Bit,
  Char,
  CodecTypes as PgTypes,
  Interval,
  JsonValue,
  Numeric,
  Time,
  TimeString,
  Timestamp,
  TimestampString,
  Timestamptz,
  TimestamptzString,
  Timetz,
  VarBit,
  Varchar,
} from '@prisma/orm-postgres/target/codec-types';

import type {
  ContractWithTypeMaps,
  RelationKeys,
  TypeMaps as TypeMapsType,
} from '@prisma/orm-postgres/family-contract/types';
import type {
  Contract as ContractType,
  ExecutionHashBase,
  NamespaceId,
  ProfileHashBase,
  StorageHashBase,
} from '@prisma/orm-postgres/contract/types';

export type StorageHash =
  StorageHashBase<'acf2aaae8bc9c6854b824a100b318166d2b430a0fff96fff2e21ac162238cf94'>;
export type ExecutionHash =
  ExecutionHashBase<'34af8f1e902723ddb6a9089851505f4b81f17afff45da6ea4c301ca3edf68c90'>;
export type ProfileHash =
  ProfileHashBase<'3916f444a8a17ad749191acf9e08dad97d1a327b88c2f1d45d12f240296aa8b2'>;

export type CodecTypes = PgTypes;
export type LaneCodecTypes = CodecTypes;
export type QueryOperationTypes = PgAdapterQueryOps<CodecTypes>;
export type AggregateTypes = {
  readonly avg: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
    };
  };
  readonly avgDecimal: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
    };
  };
  readonly count: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
  };
  readonly countBigInt: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
  };
  readonly max: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly min: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly sum: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
    };
  };
  readonly sumBigInt: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
    };
  };
};
type DefaultLiteralValue<CodecId extends string, Encoded> = CodecId extends keyof CodecTypes
  ? Encoded extends CodecTypes[CodecId]['json']
    ? Encoded
    : CodecTypes[CodecId]['json']
  : Encoded;

export type FieldOutputTypes = {
  readonly public: {
    readonly Fragment: {
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly messageId: CodecTypes['pg/text@1']['output'];
      readonly sandboxUrl: CodecTypes['pg/text@1']['output'];
      readonly title: CodecTypes['pg/text@1']['output'];
      readonly files: CodecTypes['pg/json@1']['output'];
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['output'];
    };
    readonly Message: {
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly content: CodecTypes['pg/text@1']['output'];
      readonly role: 'USER' | 'ASSISTANT';
      readonly type: 'RESULT' | 'ERROR';
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly projectId: CodecTypes['pg/text@1']['output'];
    };
    readonly Project: {
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly name: CodecTypes['pg/text@1']['output'];
      readonly userId: CodecTypes['pg/int4@1']['output'];
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['output'];
    };
    readonly User: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly clerkId: CodecTypes['pg/text@1']['output'];
      readonly email: CodecTypes['pg/text@1']['output'] | null;
      readonly firstName: CodecTypes['pg/text@1']['output'] | null;
      readonly lastName: CodecTypes['pg/text@1']['output'] | null;
      readonly name: CodecTypes['pg/text@1']['output'] | null;
      readonly imageUrl: CodecTypes['pg/text@1']['output'] | null;
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['output'];
    };
  };
};
export type FieldInputTypes = {
  readonly public: {
    readonly Fragment: {
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly messageId: CodecTypes['pg/text@1']['input'];
      readonly sandboxUrl: CodecTypes['pg/text@1']['input'];
      readonly title: CodecTypes['pg/text@1']['input'];
      readonly files: CodecTypes['pg/json@1']['input'];
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['input'];
    };
    readonly Message: {
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly content: CodecTypes['pg/text@1']['input'];
      readonly role: 'USER' | 'ASSISTANT';
      readonly type: 'RESULT' | 'ERROR';
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly projectId: CodecTypes['pg/text@1']['input'];
    };
    readonly Project: {
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly name: CodecTypes['pg/text@1']['input'];
      readonly userId: CodecTypes['pg/int4@1']['input'];
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['input'];
    };
    readonly User: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly clerkId: CodecTypes['pg/text@1']['input'];
      readonly email: CodecTypes['pg/text@1']['input'] | null;
      readonly firstName: CodecTypes['pg/text@1']['input'] | null;
      readonly lastName: CodecTypes['pg/text@1']['input'] | null;
      readonly name: CodecTypes['pg/text@1']['input'] | null;
      readonly imageUrl: CodecTypes['pg/text@1']['input'] | null;
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['input'];
    };
  };
};
export type StorageColumnTypes = {
  readonly public: {
    readonly fragment: {
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly files: CodecTypes['pg/json@1']['output'];
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly messageId: CodecTypes['pg/text@1']['output'];
      readonly sandboxUrl: CodecTypes['pg/text@1']['output'];
      readonly title: CodecTypes['pg/text@1']['output'];
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['output'];
    };
    readonly message: {
      readonly content: CodecTypes['pg/text@1']['output'];
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly projectId: CodecTypes['pg/text@1']['output'];
      readonly role: 'USER' | 'ASSISTANT';
      readonly type: 'RESULT' | 'ERROR';
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['output'];
    };
    readonly project: {
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly name: CodecTypes['pg/text@1']['output'];
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly userId: CodecTypes['pg/int4@1']['output'];
    };
    readonly user: {
      readonly clerkId: CodecTypes['pg/text@1']['output'];
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly email: CodecTypes['pg/text@1']['output'] | null;
      readonly firstName: CodecTypes['pg/text@1']['output'] | null;
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly imageUrl: CodecTypes['pg/text@1']['output'] | null;
      readonly lastName: CodecTypes['pg/text@1']['output'] | null;
      readonly name: CodecTypes['pg/text@1']['output'] | null;
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['output'];
    };
  };
};
export type StorageColumnInputTypes = {
  readonly public: {
    readonly fragment: {
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly files: CodecTypes['pg/json@1']['input'];
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly messageId: CodecTypes['pg/text@1']['input'];
      readonly sandboxUrl: CodecTypes['pg/text@1']['input'];
      readonly title: CodecTypes['pg/text@1']['input'];
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['input'];
    };
    readonly message: {
      readonly content: CodecTypes['pg/text@1']['input'];
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly projectId: CodecTypes['pg/text@1']['input'];
      readonly role: 'USER' | 'ASSISTANT';
      readonly type: 'RESULT' | 'ERROR';
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['input'];
    };
    readonly project: {
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly name: CodecTypes['pg/text@1']['input'];
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly userId: CodecTypes['pg/int4@1']['input'];
    };
    readonly user: {
      readonly clerkId: CodecTypes['pg/text@1']['input'];
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly email: CodecTypes['pg/text@1']['input'] | null;
      readonly firstName: CodecTypes['pg/text@1']['input'] | null;
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly imageUrl: CodecTypes['pg/text@1']['input'] | null;
      readonly lastName: CodecTypes['pg/text@1']['input'] | null;
      readonly name: CodecTypes['pg/text@1']['input'] | null;
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['input'];
    };
  };
};

export namespace Models {
  export type public_User = {
    id: CodecTypes['pg/int4@1']['output'];
    clerkId: CodecTypes['pg/text@1']['output'];
    email: CodecTypes['pg/text@1']['output'] | null;
    firstName: CodecTypes['pg/text@1']['output'] | null;
    lastName: CodecTypes['pg/text@1']['output'] | null;
    name: CodecTypes['pg/text@1']['output'] | null;
    imageUrl: CodecTypes['pg/text@1']['output'] | null;
    createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
    updatedAt: CodecTypes['pg/timestamptz-string@1']['output'];
    projects: public_Project[];
    readonly [RelationKeys]?: 'projects';
  };
  export type public_Project = {
    id: CodecTypes['pg/text@1']['output'];
    name: CodecTypes['pg/text@1']['output'];
    userId: CodecTypes['pg/int4@1']['output'];
    createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
    updatedAt: CodecTypes['pg/timestamptz-string@1']['output'];
    messages: public_Message[];
    user: public_User;
    readonly [RelationKeys]?: 'messages' | 'user';
  };
  export type public_Message = {
    id: CodecTypes['pg/text@1']['output'];
    content: CodecTypes['pg/text@1']['output'];
    role: 'USER' | 'ASSISTANT';
    type: 'RESULT' | 'ERROR';
    createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
    updatedAt: CodecTypes['pg/timestamptz-string@1']['output'];
    projectId: CodecTypes['pg/text@1']['output'];
    fragments: public_Fragment | null;
    project: public_Project;
    readonly [RelationKeys]?: 'fragments' | 'project';
  };
  export type public_Fragment = {
    id: CodecTypes['pg/text@1']['output'];
    messageId: CodecTypes['pg/text@1']['output'];
    sandboxUrl: CodecTypes['pg/text@1']['output'];
    title: CodecTypes['pg/text@1']['output'];
    files: CodecTypes['pg/json@1']['output'];
    createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
    updatedAt: CodecTypes['pg/timestamptz-string@1']['output'];
    message: public_Message;
    readonly [RelationKeys]?: 'message';
  };
}

export declare const models: {
  public: {
    User: Models.public_User;
    Project: Models.public_Project;
    Message: Models.public_Message;
    Fragment: Models.public_Fragment;
  };
};

export type TypeMaps = TypeMapsType<
  CodecTypes,
  QueryOperationTypes,
  FieldOutputTypes,
  FieldInputTypes,
  StorageColumnTypes,
  StorageColumnInputTypes,
  AggregateTypes
>;

type ContractBase = Omit<
  ContractType<{
    readonly namespaces: {
      readonly public: {
        readonly id: 'public';
        readonly kind: 'postgres-schema';
        readonly entries: {
          readonly table: {
            readonly fragment: {
              columns: {
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly messageId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly sandboxUrl: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly title: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly files: {
                  readonly nativeType: 'json';
                  readonly codecId: 'pg/json@1';
                  readonly nullable: false;
                };
                readonly createdAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly updatedAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [{ readonly columns: readonly ['messageId'] }];
              indexes: readonly [];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'fragment';
                    readonly columns: readonly ['messageId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'message';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly message: {
              columns: {
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly content: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly role: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly type: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly createdAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly updatedAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                };
                readonly projectId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'message_projectId_idx_a96e4d92';
                  readonly prefix: 'message_projectId_idx';
                  readonly columns: readonly ['projectId'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'message';
                    readonly columns: readonly ['projectId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'project';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly project: {
              columns: {
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly name: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly userId: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly createdAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly updatedAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'project_userId_idx_a489d58a';
                  readonly prefix: 'project_userId_idx';
                  readonly columns: readonly ['userId'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'project';
                    readonly columns: readonly ['userId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'user';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly user: {
              columns: {
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly clerkId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly email: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly firstName: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly lastName: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly name: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly imageUrl: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly createdAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly updatedAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [
                { readonly columns: readonly ['clerkId'] },
                { readonly columns: readonly ['email'] },
              ];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
          };
          readonly valueSet: {
            readonly MessageRole: {
              readonly kind: 'valueSet';
              readonly values: readonly ['USER', 'ASSISTANT'];
            };
            readonly MessageType: {
              readonly kind: 'valueSet';
              readonly values: readonly ['RESULT', 'ERROR'];
            };
          };
        };
      };
    };
    readonly storageHash: StorageHash;
  }>,
  'roots' | 'domain'
> & {
  readonly target: 'postgres';
  readonly targetFamily: 'sql';
  readonly roots: {
    readonly user: { readonly namespace: 'public' & NamespaceId; readonly model: 'User' };
    readonly project: { readonly namespace: 'public' & NamespaceId; readonly model: 'Project' };
    readonly message: { readonly namespace: 'public' & NamespaceId; readonly model: 'Message' };
    readonly fragment: { readonly namespace: 'public' & NamespaceId; readonly model: 'Fragment' };
  };
  readonly domain: {
    readonly namespaces: {
      readonly public: {
        readonly models: {
          readonly Fragment: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly messageId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly sandboxUrl: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly title: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly files: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/json@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
            };
            readonly relations: {
              readonly message: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Message';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['messageId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'fragment';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly messageId: { readonly column: 'messageId' };
                readonly sandboxUrl: { readonly column: 'sandboxUrl' };
                readonly title: { readonly column: 'title' };
                readonly files: { readonly column: 'files' };
                readonly createdAt: { readonly column: 'createdAt' };
                readonly updatedAt: { readonly column: 'updatedAt' };
              };
            };
          };
          readonly Message: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly content: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly role: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly type: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
              readonly projectId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
            };
            readonly relations: {
              readonly fragments: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Fragment';
                };
                readonly cardinality: '1:1';
                readonly nullable: true;
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['messageId'];
                };
              };
              readonly project: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Project';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['projectId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'message';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly content: { readonly column: 'content' };
                readonly role: { readonly column: 'role' };
                readonly type: { readonly column: 'type' };
                readonly createdAt: { readonly column: 'createdAt' };
                readonly updatedAt: { readonly column: 'updatedAt' };
                readonly projectId: { readonly column: 'projectId' };
              };
            };
          };
          readonly Project: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly name: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly userId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
            };
            readonly relations: {
              readonly messages: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Message';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['projectId'];
                };
              };
              readonly user: {
                readonly to: { readonly namespace: 'public' & NamespaceId; readonly model: 'User' };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['userId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'project';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly name: { readonly column: 'name' };
                readonly userId: { readonly column: 'userId' };
                readonly createdAt: { readonly column: 'createdAt' };
                readonly updatedAt: { readonly column: 'updatedAt' };
              };
            };
          };
          readonly User: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly clerkId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly email: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly firstName: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly lastName: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly name: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly imageUrl: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
            };
            readonly relations: {
              readonly projects: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Project';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['userId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'user';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly clerkId: { readonly column: 'clerkId' };
                readonly email: { readonly column: 'email' };
                readonly firstName: { readonly column: 'firstName' };
                readonly lastName: { readonly column: 'lastName' };
                readonly name: { readonly column: 'name' };
                readonly imageUrl: { readonly column: 'imageUrl' };
                readonly createdAt: { readonly column: 'createdAt' };
                readonly updatedAt: { readonly column: 'updatedAt' };
              };
            };
          };
        };
        readonly enum: {
          readonly MessageRole: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'USER'; readonly value: 'USER' },
              { readonly name: 'ASSISTANT'; readonly value: 'ASSISTANT' },
            ];
          };
          readonly MessageType: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'RESULT'; readonly value: 'RESULT' },
              { readonly name: 'ERROR'; readonly value: 'ERROR' },
            ];
          };
        };
      };
    };
  };
  readonly capabilities: {
    readonly postgres: {
      readonly distinctOn: true;
      readonly jsonAgg: true;
      readonly lateral: true;
      readonly limit: true;
      readonly orderBy: true;
      readonly returning: true;
    };
    readonly sql: {
      readonly checkConstraint: true;
      readonly defaultInInsert: true;
      readonly enums: true;
      readonly lateral: true;
      readonly returning: true;
      readonly scalarList: true;
    };
  };
  readonly extensions: {};
  readonly execution: {
    readonly executionHash: ExecutionHash;
    readonly mutations: {
      readonly defaults: readonly [
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'fragment';
            readonly column: 'id';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'uuidv4' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'fragment';
            readonly column: 'updatedAt';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'timestampNow' };
          readonly onUpdate: { readonly kind: 'generator'; readonly id: 'timestampNow' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'message';
            readonly column: 'id';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'uuidv4' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'message';
            readonly column: 'updatedAt';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'timestampNow' };
          readonly onUpdate: { readonly kind: 'generator'; readonly id: 'timestampNow' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'project';
            readonly column: 'id';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'uuidv4' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'project';
            readonly column: 'updatedAt';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'timestampNow' };
          readonly onUpdate: { readonly kind: 'generator'; readonly id: 'timestampNow' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'user';
            readonly column: 'updatedAt';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'timestampNow' };
          readonly onUpdate: { readonly kind: 'generator'; readonly id: 'timestampNow' };
        },
      ];
    };
  };
  readonly meta: {};

  readonly profileHash: ProfileHash;
};

export type Contract = ContractWithTypeMaps<ContractBase, TypeMaps>;

export type Namespaces = Contract['storage']['namespaces'];
